### ISSUE TITLE
Android icon

### ISSUE THREAD

**Issue by bastien70** [twbs/icons#1175]
Hello, there is the Apple icon but not the Android icon.
So bad if we have to display some AppStore and PlayStore buttons

**Comment by PanderMusubi** [comment]
I noticed the space between the torso and the arms are clear but between the head and the torso is very small. Comparing the original (green) and the icon here (transparent balck), you can see the arms are given more space. Which is good because most of the icons here are used small.

Perhaps good to also give more space between the head and the torso? Or support the original version 100%. Wondering what the ideas are here.

![Screenshot from 2022-08-24 13-38-17](https://user-images.githubusercontent.com/198964/186409132-e7b5f164-b7cf-460c-9188-9bdca485ffd4.png)
