### ISSUE TITLE
Suggestion: Use Combining Characters

### ISSUE THREAD

**Issue by emeraldinspirations** [twbs/icons#1497]
In some font formats (not sure if it works for web fonts) you can super-impose one glyph on another.  This is usually used for diacritical marks.  See: <https://en.wikipedia.org/wiki/Combining_character>

This feature can greatly simplify the status indicators on icons.  Having one status glyph (`exclamation`, `gear`, `lock`, `slash`, etc) can then combine with any of the existing base glyphs greatly reducing the total number of glyphs and increasing the flexibility for the user.

**Comment by korki43** [comment]
Do you mean eg. combining the characters for [exclamation](https://icons.getbootstrap.com/icons/exclamation/) and [circle](https://icons.getbootstrap.com/icons/circle/) to create [exclamation-circle](https://icons.getbootstrap.com/icons/exclamation-circle/)?

Theoretically it's a nice idea but it wouldn't really work with the way icons are created at the moment, because each icon is defined in one SVG file. I also believe the library used to create the font files isn't capable of creating combining characters. Lastly, I'm not sure if these characters are supported everywhere.

**Comment by emeraldinspirations** [comment]
@korki43 

More like [building](https://icons.getbootstrap.com/icons/building/) and `dash` creates [building-dash](https://icons.getbootstrap.com/icons/building-dash/), but it can work in multiple scenarios (including your example).

Thank you for the response.  Feel free to use this idea in the future if things change.  I assume I close now.
