### ISSUE TITLE
Revisit how we include Bootstrap source files

### ISSUE THREAD

**Issue by mdo** [twbs/icons#589]
- Include via npm?
- Custom builds of CSS and JS?
- Some kind of templating from upstream main repo?

/cc @XhmikosR

**Comment by XhmikosR** [comment]
I think we better build a customm Bootstrap build ourselves here.

Pros:

1. no purgecss thus less devDependencies
2. same prod and dev files

Cons:

1. Hugo's built-in Sass will be used which isn't something we use elsewhere apart from the docs here and upstream
2. Due to the aforementioned point, build might be a little slower, but still fast

**Comment by mdo** [comment]
This was done in v1.8.2.
