### ISSUE TITLE
Suggestion to Make SVG color changes simple

### ISSUE THREAD

**Issue by JacobLett** [twbs/icons#71]
Thank you for creating these icons. One suggestion I have would be to add some support on shifting colors of the svgs with the image tag. Either using CSS color filters or js to change the color. 

Here is an example - https://blog.union.io/code/2017/08/10/img-svg-fill/

For beginners, svg's are confusing with all of the coordinates. So I think it would be nice to make svg's work the same way as jpegs and pngs... with the additional super powers of scaling and color changing.

Here is a codepen experimenting with filters - https://codepen.io/JacobLett/pen/LYYwQjz

**Comment by mdo** [comment]
> One suggestion I have would be to add some support on shifting colors of the svgs with the image tag. Either using CSS color filters or js to change the color.

If you or someone else has a formula for turning hex values into `filter`s, I'd love to see it. Otherwise, this seems like a bit problematic for us to handle.

> For beginners, svg's are confusing with all of the coordinates.

Beginners don't need to touch SVG source code. Our docs include specific mentions of how to change colors with another implementation method. I think that's good enough for most folks.

> So I think it would be nice to make svg's work the same way as jpegs and pngs.

No plans to add another file format. SVG is the way to go here—file size, icon image size, customization, scriptability, etc.
