### ISSUE TITLE
Gaming Platforms

### ISSUE THREAD

**Issue by Chipsum** [twbs/icons#905]
Xbox , Nintendo Switch , PlayStation, Steam, ..etc

**Comment by kylek14** [comment]
@mdo I can pick this up since I finished the Windows + Microsoft/Mac if you have no complaints.

**Comment by nils-kt** [comment]
> @mdo I can pick this up since I finished the Windows + Microsoft/Mac if you have no complaints.

Any update?

**Comment by kylek14** [comment]
> > @mdo I can pick this up since I finished the Windows + Microsoft/Mac if you have no complaints.
> 
> Any update?

Since my initial PR was accepted, I can start working on these.

Looking at the following icons so far. 

- [ ] Xbox
- [ ] Playstation
- [ ] Steam
- [ ] Uplay
- [ ] Epic Store
- [ ] Battle.net
- [ ] itch.io
- [ ] Origin
- [ ] GOG

After looking at other icon sets, I'm going to suggest we hold off on creating any Nintendo-themed icons for the moment. Nintendo tends to protect their IP aggressively and I don't want to put Bootstrap in hot water.

**Comment by shaunroselt** [comment]
Any update on a release date for these icons?

**Comment by vanillajonathan** [comment]
Microsoft Store.

Maybe related are [Flatpak](https://flatpak.org/) and [Snap](https://snapcraft.io/).

**Comment by kylek14** [comment]
@mdo sorry work was kicking my butt and didn't get a chance to respond back to y'all. I'm still down for taking care of these more obscure ones if you haven't already tackled them. I'll start working on these here shortly.
