### ISSUE TITLE
Icon request all social media icon

### ISSUE THREAD

**Issue by dropways** [twbs/icons#96]

**Comment by mdo** [comment]
Been waiting for this request to roll in, but I feel like snagging the SVGs for all these networks is easy enough these days. Unsure how much I want to get into that, as I think many companies have constraints how their brand assets are modified and distributed.

**Comment by coliff** [comment]
Font Awesome has 442 brand icons.
https://fontawesome.com/icons?s=brands
I think adding social media icons could turn into a big job maintaining it as some new channels are added, some close down and other change their icons etc. Plus I'm sure there'll be request to add icons within circles and squares and so on....
The brand icons from the Font Awesome repo are open-source and available as SVG... so I wonder if it'd make more sense to point folks there if they want to use them rather than duplicating all that work.

**Comment by vanillajonathan** [comment]
The major ones are the most important ones:

- Google
- Facebook
- Twitter
- Instagram
- YouTube

Also nice ones to have.

- GitHub
- GitLab
- Slack
- Twitch

**Comment by DimIsaev** [comment]
+ Tik tok

**Comment by literakl** [comment]
Fontawesome free plan is limited to 10K Pageviews/Month. So it can be used for hobby projects only.

Please consider adding the most popular social networks. I am not a lawyer so I am not sure if the license permits the reuse but iconmaster has many icons in SVG. Shall I ask them for consent?

https://iconmonstr.com/license/
https://iconmonstr.com/logos/

**Comment by saturdaywalkers** [comment]
A bit unfair to copy them from Font Awesome.
But they are needed. People aren't going to use 2 icons libraries. BS, then FA just for the brand icons.
Also, Amazon, Android, Apple etc. (and their Asian equivalents) ... about 50 icons should get you 95% of what people need.

**Comment by thewebartisan7** [comment]
You can download only single SVG of fontawesome from here:

Facebook:
https://icongr.am/fontawesome/facebook.svg?size=128&color=currentColor
Google:
https://icongr.am/fontawesome/google.svg?size=128&color=currentColor

Etc...

See here all https://icongr.am/fontawesome/

**Comment by omniboy** [comment]
I don't mean to stress this but this issue is about to hit its "birthday" in a month. Like mdo commented, it would be nice to get the social media icons rolled out because they're probably one of the most anticipated icons. I gotta give you credit. Your icons look really awesome but I'm not in for using two different icon kits because BS icons are lacking the social media ones.

**Comment by vanillajonathan** [comment]
Notably absent is YouTube.

**Comment by vanillajonathan** [comment]
YouTube and Discord have since been added. Still none for GitLab though.

**Comment by vanillajonathan** [comment]
Facebook Messenger, Reddit, Skype, WhatsApp, Mastodon and YouTube have since been added.
Notably absent is GitLab. #785

**Comment by mdo** [comment]
Please keep requests on track. Language icons are covered by #812.

Some of these I don't plan to do, either at all or even looking ahead shorter term. I've opened a new issue to track the additional social icons I do think I'll add—see #883.

**Comment by vanillajonathan** [comment]
Some more social media icons are mentioned in the #898 issue.
